### ISSUE TITLE
`&` character displayed as `\u0026` in strings

### ISSUE THREAD

**Issue by asciimoo** [nwidger/jsoncolor#1]
I couldn't find any option to disable this behavior so I suppose, it is a bug.

Example JSON to reproduce:
```json
{
  "url": "https://httpbin.org/get?x=3&y=3"
}
```
Could you confirm?

**Comment by asciimoo** [comment]
Awesome, it works well! Thanks the quick fix.

**Comment by nwidger** [comment]
You're welcome!
