### ISSUE TITLE
Would you turn it into a lib?

### ISSUE THREAD

**Issue by suntong** [nwidger/jsoncolor#3]
Would you consider turning it into a lib so that other go code can use it as well please? Thx.

**Comment by nwidger** [comment]
@suntong Sorry, I'm confused by your question.  This package is a library and is used by at least three other packages: https://godoc.org/github.com/nwidger/jsoncolor?importers

What would you like to do with jsoncolor that you're currently not able to do?

**Comment by suntong** [comment]
Ops, sorry my bad. This package is a library **already**.
