### ISSUE TITLE
Create a release tag

### ISSUE THREAD

**Issue by protoCall7** [nwidger/jsoncolor#4]
I am currently working on packaging jsoncolor as a dependency of another project which I am porting to OpenBSD. OpenBSD packaging requires that a version be associated with the software. Would it be possible to tag a release of jsoncolor?

**Comment by nwidger** [comment]
Absolutely!  I just created a v0.1.0 tag.  Out of curiosity, what project are you porting that uses jsoncolor?

**Comment by protoCall7** [comment]
Thanks so much nwidger! I'm currently porting a tool called `gron` that converts JSON blobs into a greppable format. https://github.com/tomnomnom/gron

**Comment by nwidger** [comment]
Ah yes, gron's great tool.  The `jsoncolor` dependency was actually due to my shameless self-promotion :P

https://github.com/tomnomnom/gron/pull/11
