### ISSUE TITLE
Encoder does not print newlines

### ISSUE THREAD

**Issue by colinking** [nwidger/jsoncolor#5]
Here's an example: https://goplay.space/#aJgJu9bSfOV

From looking at the code, it looks like the encoder prints a newline via `printSpace` which is disabled if `compact=true`. AFAICT, those are only relevant to `MarshalIndent`.

**Comment by colinking** [comment]
Here's the corresponding `encoding/json` version which does print the newline: https://goplay.space/#35zNP_wOjQy

**Comment by nwidger** [comment]
@colinking Thanks for reporting this issue!  I opened a PR #6 that I hope will fix this issue.  Would you mind trying out the `issue-5-encoder-does-not-print-newlines` branch and letting me know?

**Comment by colinking** [comment]
Thanks for such a quick fix @nwidger! Sorry about the delay. Just gave it a test. LGTM!
