### ISSUE TITLE
output of a JON scalar contains a leading space

### ISSUE THREAD

**Issue by springcomp** [nwidger/jsoncolor#7]
When printing `null`, `true`, `false`, any number or a string, the library prepends a leading space.
This is a slight deviation from the original "encoding/json" behaviour.

**Comment by nwidger** [comment]
@springcomp Thanks for opening this issue and submitting a PR!  What version of Go are you seeing this issue with and would it be possible to provide a code snippet to reproduce the issue you're seeing?  Based on the issue description, I tried to create a reproduction scenario but I'm not seeing any leading spaces:

https://go.dev/play/p/VYCQzPvuQBh

If you could provide an example that does, that'd be great.

**Comment by springcomp** [comment]
> If you could provide an example that does, that'd be great.

Here is a repro case:

https://go.dev/play/p/MlL9hK9WsAp

**Comment by nwidger** [comment]
Thanks!  Now that I understand the issue, I'll try to take a look at your PR soon.
